# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'')),
                ('time', models.DateTimeField()),
                ('scene', models.IntegerField()),
            ],
        ),
    ]
