# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamimagemodel',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
