# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamimages', '0002_auto_20190202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamimagemodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='img'),
        ),
    ]
